-- TikTok 주문 데이터를 저장할 테이블 생성
CREATE TABLE IF NOT EXISTS tiktok_orders (
  id SERIAL PRIMARY KEY,
  order_id BIGINT,
  order_status TEXT,
  order_substatus TEXT,
  cancelation_return_type TEXT,
  normal_or_preorder TEXT,
  sku_id BIGINT,
  seller_sku TEXT,
  product_name TEXT,
  variation TEXT,
  quantity INTEGER,
  sku_quantity_of_return INTEGER,
  sku_unit_original_price DECIMAL(10,2),
  sku_subtotal_before_discount DECIMAL(10,2),
  sku_platform_discount DECIMAL(10,2),
  sku_seller_discount DECIMAL(10,2),
  sku_subtotal_after_discount DECIMAL(10,2),
  shipping_fee_after_discount DECIMAL(10,2),
  original_shipping_fee DECIMAL(10,2),
  shipping_fee_seller_discount DECIMAL(10,2),
  co_funded_shipping_fee_discount DECIMAL(10,2),
  shipping_fee_platform_discount DECIMAL(10,2),
  payment_platform_discount DECIMAL(10,2),
  retail_delivery_fee DECIMAL(10,2),
  taxes DECIMAL(10,2),
  order_amount DECIMAL(10,2),
  order_refund_amount DECIMAL(10,2),
  created_time TIMESTAMP,
  paid_time TIMESTAMP,
  rts_time TIMESTAMP,
  shipped_time TIMESTAMP,
  delivered_time TIMESTAMP,
  cancelled_time TIMESTAMP,
  cancel_by TEXT,
  cancel_reason TEXT,
  fulfillment_type TEXT,
  warehouse_name TEXT,
  tracking_id TEXT,
  delivery_option_type TEXT,
  delivery_option TEXT,
  shipping_provider_name TEXT,
  buyer_message TEXT,
  buyer_username TEXT,
  recipient TEXT,
  phone_number TEXT,
  country TEXT,
  state TEXT,
  city TEXT,
  zipcode TEXT,
  address_line_1 TEXT,
  address_line_2 TEXT,
  delivery_instruction TEXT,
  payment_method TEXT,
  weight_kg DECIMAL(10,3),
  product_category TEXT,
  package_id BIGINT,
  seller_note TEXT,
  shipping_information TEXT,
  combined_listing TEXT,
  uploaded_at TIMESTAMP DEFAULT NOW()
);

-- 인덱스 생성 (성능 향상을 위해)
CREATE INDEX IF NOT EXISTS idx_tiktok_orders_created_time ON tiktok_orders(created_time);
CREATE INDEX IF NOT EXISTS idx_tiktok_orders_shipped_time ON tiktok_orders(shipped_time);
CREATE INDEX IF NOT EXISTS idx_tiktok_orders_product_name ON tiktok_orders(product_name);
CREATE INDEX IF NOT EXISTS idx_tiktok_orders_order_status ON tiktok_orders(order_status);
