#!/bin/bash

# 16x16 파란색 PNG (base64)
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5wEeABcKz3t3SAAAADZJREFUOMtjZGBg+M9AAWBioBBQxYD/DPQBozCAkfE/wwgwgJGB4T8t8TDqgkE4jI16YRAaAABXGAURSryGXAAAAABJRU5ErkJggg==" | base64 -d > images/icon16.png

# 48x48 파란색 PNG (base64)
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5wEeABgRt1+NewAAADtJREFUaN7t0KENACAMA8GOxv7LUoKAhCTvJu2XVBERERERERERERERERGRf7TM3FeZmau7z7yIiIiIbB5wTwUR8LMXUQAAAABJRU5ErkJggg==" | base64 -d > images/icon48.png

# 128x128 파란색 PNG (base64)
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5wEeABkJlP+TDQAAAEFJREFUeNrt0IEJACAIBEBd1P2XdQKjQBD8O/gPFBERERERERERERERERERERERERERERERERERERERERERERGR4w3VmgQRWLGO0AAAAABJRU5ErkJggg==" | base64 -d > images/icon128.png

echo "Icons created successfully!"